[tools]
# Unix Command Alternatives
bat = "sharkdp/bat@0.25.0"            # replaces cat
bottom = "ClementTsang/bottom@0.10.2" # replaces top
delta = "dandavison/delta@0.18.2"     # replaces diff
dust = "bootandy/dust@1.2.2"          # replaces du
fd = "sharkdp/fd@10.2.0"              # replaces find
lsd = "lsd-rs/lsd@1.1.5"              # replaces ls
procs = "dalance/procs@0.14.10"       # replaces ps
rg = "burntsushi/ripgrep@14.1.1"      # replaces grep
sd = "chmln/sd@1.0.0"                 # replaces sed
skim = "skim-rs/skim@0.20.2"          # replaces fzf
zoxide = "ajeetdsouza/zoxide@0.9.8"   # replaces cd

luau-lsp = "JohnnyMorganz/luau-lsp@1.53.0"
