import TokenType from "./token-type";

export interface Metadata {
	readonly name: string;
}

const TokenTypeMeta: Readonly<Record<TokenType, Metadata>> = {
	[TokenType.ALIGNED_CFRAME]: { name: "AlignedCFrame" },
	[TokenType.ARGS]: { name: "args" },
	[TokenType.BOOLEAN]: { name: "boolean" },
	[TokenType.BOOLEAN_LITERAL]: { name: "boolean literal" },
	[TokenType.BRICK_COLOR]: { name: "BrickColor" },
	[TokenType.CALL]: { name: "call" },
	[TokenType.CFRAME]: { name: "CFrame" },
	[TokenType.COLON]: { name: ":" },
	[TokenType.COLOR3]: { name: "Color3" },
	[TokenType.COMMA]: { name: "," },
	[TokenType.COMMENT]: { name: "comment" },
	[TokenType.DATA]: { name: "data" },
	[TokenType.DATETIME]: { name: "DateTime" },
	[TokenType.DATETIME_MILLIS]: { name: "DateTimeMillis" },
	[TokenType.DOT_DOT]: { name: ".." },
	[TokenType.ENUM]: { name: "enum" },
	[TokenType.EOF]: { name: "end of file" },
	[TokenType.EQUALS]: { name: "=" },
	[TokenType.EVENT]: { name: "event" },
	[TokenType.F32]: { name: "f32" },
	[TokenType.F64]: { name: "f64" },
	[TokenType.FROM]: { name: "from" },
	[TokenType.FUNCT]: { name: "funct" },
	[TokenType.GREATER_THAN]: { name: ">" },
	[TokenType.I8]: { name: "i8" },
	[TokenType.I16]: { name: "i16" },
	[TokenType.I32]: { name: "i32" },
	[TokenType.IDENTIFIER]: { name: "identifier" },
	[TokenType.INSTANCE]: { name: "Instance" },
	[TokenType.LEFT_BRACE]: { name: "{" },
	[TokenType.LEFT_BRACKET]: { name: "[" },
	[TokenType.LEFT_PAREN]: { name: "(" },
	[TokenType.LESS_THAN]: { name: "<" },
	[TokenType.MAP]: { name: "map" },
	[TokenType.NAMESPACE]: { name: "namespace" },
	[TokenType.NEWLINE]: { name: "newline" },
	[TokenType.NUMBER_LITERAL]: { name: "number" },
	[TokenType.OPT]: { name: "opt" },
	[TokenType.PIPE]: { name: "|" },
	[TokenType.QUESTION]: { name: "?" },
	[TokenType.RETS]: { name: "rets" },
	[TokenType.RIGHT_BRACE]: { name: "}" },
	[TokenType.RIGHT_BRACKET]: { name: "]" },
	[TokenType.RIGHT_PAREN]: { name: ")" },
	[TokenType.SET]: { name: "set" },
	[TokenType.STRING]: { name: "string" },
	[TokenType.STRING_LITERAL]: { name: "string literal" },
	[TokenType.STRUCT]: { name: "struct" },
	[TokenType.TYPE]: { name: "type" },
	[TokenType.U8]: { name: "u8" },
	[TokenType.U16]: { name: "u16" },
	[TokenType.U32]: { name: "u32" },
	[TokenType.UNKNOWN]: { name: "unknown" },
	[TokenType.VECTOR]: { name: "Vector" },
	[TokenType.VECTOR2]: { name: "Vector2" },
	[TokenType.VECTOR3]: { name: "Vector3" },
	[TokenType.WHITESPACE]: { name: "whitespace" },
};

export default TokenTypeMeta;
